version: "3"

services:
  dermis-bot:
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/dermis
    networks:
      - dermis-discord-bot
    depends_on:
      - mysqldb
    restart: on-failure

  mysqldb:
    image: mysql:latest
    networks:
      - dermis-discord-bot
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dermis

networks:
  dermis-discord-bot: