spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dermis
        username: root
        password:
    jpa:
        generate-ddl: true
        hibernate.ddl-auto: create-drop

discord:
    credentials:
        token: NzU2MDI5MTgxMDAyNzc2NjU5.GIKMiV.rU4I3dcIfxnd_9-pSjw4En9KxRUZGpV1s-E4SM
    commands:
        register: 1098286988517453957
        status: 1100439058074837054

payment:
    invoice-date: 11
    monthly-price: 34.00
